apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-storage
spec:
  storageClassName: seaweedfs-storage-nvme
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi