apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  containers:
  - name: gpu-container
    image: gitlab-registry.nrp-nautilus.io/zihaozhou/nautilus_tutorial:jupyterhub
    command: ["jupyter", "lab", "--NotebookApp.token=161000"]
    volumeMounts:
    - mountPath: /home/jovyan/ucl-ids
      name: persistent-storage
    resources:
      limits:
        nvidia.com/gpu: "1"
        memory: "8G"
        cpu: "4"
  restartPolicy: Never
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: persistent-storage